### ISSUE TITLE
[BUG] chowdsp_juce_dsp fails to compile with JUCE-6.1.3

### ISSUE THREAD

**Issue by KottV** [jatinchowdhury18/AnalogTapeModel#241]
**Describe the bug**
It builds fine with JUCE-6.1.2 but fails with 6.1.3 or newer

**To Reproduce**
git clone the repo
replace `AnalogTapeModel/Plugin/modules/JUCE` with the recent version
try to build

**Expected behavior**
successfull build

**Screenshots**
you'll got an errors with `JUCE_DEPRECATED_WITH_BODY` in `AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h`:

```
In file included from /home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/chowdsp_juce_dsp.h:253,
                 from /home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/chowdsp_juce_dsp.cpp:35:
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:78:46: error: expected identifier before ‘:’ token
   78 |         JUCE_DEPRECATED_WITH_BODY (Filter(), : parameters (new Parameters<NumericType>) { reset(); })
      |                                              ^
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:78:46: error: expected ‘,’ or ‘...’ before ‘:’ token
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:78:9: error: ISO C++ forbids declaration of ‘JUCE_DEPRECATED_WITH_BODY’ with no type [-fpermissive]
   78 |         JUCE_DEPRECATED_WITH_BODY (Filter(), : parameters (new Parameters<NumericType>) { reset(); })
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:78:101: error: expected ‘;’ at end of member declaration
   78 |         JUCE_DEPRECATED_WITH_BODY (Filter(), : parameters (new Parameters<NumericType>) { reset(); })
      |                                                                                                     ^
      |                                                                                                      ;
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:85:76: error: expected identifier before ‘:’ token
   85 |         JUCE_DEPRECATED_WITH_BODY (Filter (ParametersPtr parametersToUse), : parameters (std::move (parametersToUse)) { reset(); })
      |                                                                            ^
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:85:76: error: expected ‘,’ or ‘...’ before ‘:’ token
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:85:9: error: ISO C++ forbids declaration of ‘JUCE_DEPRECATED_WITH_BODY’ with no type [-fpermissive]
   85 |         JUCE_DEPRECATED_WITH_BODY (Filter (ParametersPtr parametersToUse), : parameters (std::move (parametersToUse)) { reset(); })
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/chowdsp_juce_dsp.h:253,
                 from /home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/chowdsp_juce_dsp.cpp:35:
/home/kv/src/audio/AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/juce_StateVariableFilter.h:85:131: error: expected ‘;’ at end of member declaration
   85 |         JUCE_DEPRECATED_WITH_BODY (Filter (ParametersPtr parametersToUse), : parameters (std::move (parametersToUse)) { reset(); })
      |                                                                                                                                   ^
      |                                                                                                                                    ;
```

**Desktop (please complete the following information):**
 - OS: openSUSE TW
 - DAW any
 - Version HEAD

**Additional context**

It's easy to fix by update `AnalogTapeModel/Plugin/modules/chowdsp_juce_dsp/processors/*` with same files from JUCE, but i'm not sure if it's safe

**Comment by jatinchowdhury18** [comment]
Hi Konstantin! Thanks for catching this. I've gone ahead and updated the `chowdsp_juce_dsp` repo, as well as adding some notes to the README about exactly which files have changed, and how to update the repo when necessary.

Since the relevant breaking change is not compatible with JUCE 6.1.2, I've updated this repo on a separate branch `juce-6.1.3`, if you want to test from there. Once the lv2-porting-project JUCE fork is on 6.1.3, I can merge everything from there!

Thanks,
Jatin

**Comment by KottV** [comment]
Hi!
Cool. I made a separate branch [6.1.4-lv2](https://github.com/lv2-porting-project/JUCE/tree/6.1.4-lv2), will do some tests, then report you back

**Comment by KottV** [comment]
https://github.com/lv2-porting-project/JUCE/tree/lv2 is updated to 6.1.4
Thanks!
